# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agentgate_pb2 as agentgate__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agentgate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentGateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestGrant = channel.unary_unary(
                '/agentgate.AgentGate/RequestGrant',
                request_serializer=agentgate__pb2.GrantRequest.SerializeToString,
                response_deserializer=agentgate__pb2.GrantResponse.FromString,
                _registered_method=True)
        self.ExchangeGrant = channel.unary_unary(
                '/agentgate.AgentGate/ExchangeGrant',
                request_serializer=agentgate__pb2.ExchangeRequest.SerializeToString,
                response_deserializer=agentgate__pb2.ExchangeResponse.FromString,
                _registered_method=True)
        self.ReleaseGrant = channel.unary_unary(
                '/agentgate.AgentGate/ReleaseGrant',
                request_serializer=agentgate__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=agentgate__pb2.ReleaseResponse.FromString,
                _registered_method=True)
        self.RevokeAgent = channel.unary_unary(
                '/agentgate.AgentGate/RevokeAgent',
                request_serializer=agentgate__pb2.RevokeAgentRequest.SerializeToString,
                response_deserializer=agentgate__pb2.RevokeAgentResponse.FromString,
                _registered_method=True)
        self.EvaluatePolicy = channel.unary_unary(
                '/agentgate.AgentGate/EvaluatePolicy',
                request_serializer=agentgate__pb2.PolicyEvalRequest.SerializeToString,
                response_deserializer=agentgate__pb2.PolicyEvalResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/agentgate.AgentGate/HealthCheck',
                request_serializer=agentgate__pb2.HealthRequest.SerializeToString,
                response_deserializer=agentgate__pb2.HealthResponse.FromString,
                _registered_method=True)


class AgentGateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentGateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestGrant,
                    request_deserializer=agentgate__pb2.GrantRequest.FromString,
                    response_serializer=agentgate__pb2.GrantResponse.SerializeToString,
            ),
            'ExchangeGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeGrant,
                    request_deserializer=agentgate__pb2.ExchangeRequest.FromString,
                    response_serializer=agentgate__pb2.ExchangeResponse.SerializeToString,
            ),
            'ReleaseGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseGrant,
                    request_deserializer=agentgate__pb2.ReleaseRequest.FromString,
                    response_serializer=agentgate__pb2.ReleaseResponse.SerializeToString,
            ),
            'RevokeAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAgent,
                    request_deserializer=agentgate__pb2.RevokeAgentRequest.FromString,
                    response_serializer=agentgate__pb2.RevokeAgentResponse.SerializeToString,
            ),
            'EvaluatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluatePolicy,
                    request_deserializer=agentgate__pb2.PolicyEvalRequest.FromString,
                    response_serializer=agentgate__pb2.PolicyEvalResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agentgate__pb2.HealthRequest.FromString,
                    response_serializer=agentgate__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentgate.AgentGate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentgate.AgentGate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentGate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentgate.AgentGate/RequestGrant',
            agentgate__pb2.GrantRequest.SerializeToString,
            agentgate__pb2.GrantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentgate.AgentGate/ExchangeGrant',
            agentgate__pb2.ExchangeRequest.SerializeToString,
            agentgate__pb2.ExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentgate.AgentGate/ReleaseGrant',
            agentgate__pb2.ReleaseRequest.SerializeToString,
            agentgate__pb2.ReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentgate.AgentGate/RevokeAgent',
            agentgate__pb2.RevokeAgentRequest.SerializeToString,
            agentgate__pb2.RevokeAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentgate.AgentGate/EvaluatePolicy',
            agentgate__pb2.PolicyEvalRequest.SerializeToString,
            agentgate__pb2.PolicyEvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentgate.AgentGate/HealthCheck',
            agentgate__pb2.HealthRequest.SerializeToString,
            agentgate__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
